import type {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {registerStartLogin} from './start-login.js';
import {registerCompleteLogin} from './complete-login.js';
import {registerListWorkspaces} from './list-workspaces.js';
import {registerListAccounts} from './list-accounts.js';
import {registerListBenefits} from './list-benefits.js';
import {registerListCurrencies} from './list-currencies.js';
import {registerListTransactions} from './list-transactions.js';
import {registerGetExpense} from './get-expense.js';
import {registerGetBenefitSchedule} from './get-benefit-schedule.js';
import {registerGetCurrentUser} from './get-current-user.js';
import {registerGetSubstantiationRequirements} from './get-substantiation-requirements.js';
import {registerUploadReceipt} from './upload-receipt.js';
import {registerSubmitExpense} from './submit-expense.js';
import {registerUpdateExpense} from './update-expense.js';
import {registerCallApi} from './call-api.js';
import {registerListCards} from './list-cards.js';
import {registerGetCard} from './get-card.js';
import {registerListAvailableCards} from './list-available-cards.js';
import {registerListBankAccounts} from './list-bank-accounts.js';
import {registerListDocuments} from './list-documents.js';
import {registerGetDocument} from './get-document.js';
import {registerListTasks} from './list-tasks.js';
import {registerGetEmployment} from './get-employment.js';
import {registerConvertCurrency} from './convert-currency.js';
import {registerListMerchants} from './list-merchants.js';
import {registerGetMerchant} from './get-merchant.js';
import {registerListForms} from './list-forms.js';
import {registerGetForm} from './get-form.js';
import {registerListIdentities} from './list-identities.js';
import {registerListOnboardings} from './list-onboardings.js';
import {registerGetOnboarding} from './get-onboarding.js';
import {registerGetHsaAccountDetails} from './get-hsa-account-details.js';

export function registerAll(server: McpServer): void {
	registerStartLogin(server);
	registerCompleteLogin(server);
	registerListWorkspaces(server);
	registerListAccounts(server);
	registerListBenefits(server);
	registerListCurrencies(server);
	registerListTransactions(server);
	registerGetExpense(server);
	registerGetBenefitSchedule(server);
	registerGetCurrentUser(server);
	registerGetSubstantiationRequirements(server);
	registerUploadReceipt(server);
	registerSubmitExpense(server);
	registerUpdateExpense(server);
	registerCallApi(server);
	registerListCards(server);
	registerGetCard(server);
	registerListAvailableCards(server);
	registerListBankAccounts(server);
	registerListDocuments(server);
	registerGetDocument(server);
	registerListTasks(server);
	registerGetEmployment(server);
	registerConvertCurrency(server);
	registerListMerchants(server);
	registerGetMerchant(server);
	registerListForms(server);
	registerGetForm(server);
	registerListIdentities(server);
	registerListOnboardings(server);
	registerGetOnboarding(server);
	registerGetHsaAccountDetails(server);
}
